package mylibrary;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class LibLogin extends javax.swing.JFrame {

    private String username;
    

    /**
     * Creates new form LibLogin
     */
    public LibLogin() {
        initComponents();
        setTitle("Library Login");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(800, 500)); 
        pack(); 
        setLocationRelativeTo(null);
        setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLogButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JRegButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\MyLibraryy\\src\\Bookw (2).png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(810, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\MyLibrary\\src\\Bookw (2).png")); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(319, 460));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 474, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -11, 310, 480));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 150, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.darkGray);
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 80, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.darkGray);
        jLabel4.setText("Username or Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 130, -1));

        jTextField2.setBackground(new java.awt.Color(213, 224, 227));
        jTextField2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 430, 40));

        jPasswordField1.setBackground(new java.awt.Color(213, 224, 227));
        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 430, 40));

        jLogButton.setBackground(new java.awt.Color(137, 168, 185));
        jLogButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLogButton.setForeground(new java.awt.Color(51, 51, 51));
        jLogButton.setText("Login");
        jLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jLogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 110, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("You don't have an account yet?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 250, 50));

        JRegButton.setBackground(new java.awt.Color(189, 193, 195));
        JRegButton.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        JRegButton.setForeground(new java.awt.Color(51, 51, 51));
        JRegButton.setText("Register");
        JRegButton.setBorder(null);
        JRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRegButtonActionPerformed(evt);
            }
        });
        getContentPane().add(JRegButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 70, 30));

        jLabel7.setBackground(new java.awt.Color(213, 224, 227));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\MyLibrary\\src\\1.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 500, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        jPasswordField1.requestFocusInWindow();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogButtonActionPerformed
        // TODO add your handling code here:
       
        String usernameOrEmail = jTextField2.getText();
        String password = new String(jPasswordField1.getPassword());

        User user = validateLogin(usernameOrEmail, password);

        if (user != null) {
            // Check if the user is active (assuming 1 is active and 0 is inactive)
            if (user.getActive() == 0) { // Replace this line with the appropriate method to get the active status
                JOptionPane.showMessageDialog(this, "Your account is inactive. Please contact support.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                jTextField2.setText(""); // Clear username/email field
                jPasswordField1.setText(""); // Clear password field
                return; // Exit the method to prevent further processing
            }

            // Check user role
            String role = getUserRole(user.getUserId());
            if ("admin".equalsIgnoreCase(role)) {
                // If the user is an admin, show Admin UI
                int userId = user.getUserId(); // Get the admin's userId
                String username = user.getUsername(); // Get the admin's username
                AdminUI adminUI = new AdminUI(userId, username); // Pass the userId and username
                adminUI.setVisible(true); // Show the Admin UI
                this.dispose(); // Close the login form
            } else {
                // If the user is a regular user, show LibDashboard
                LibDashboard dashboard = new LibDashboard(user.getUserId(), user.getUsername());
                dashboard.setVisible(true);
                dashboard.pack();
                dashboard.setLocationRelativeTo(null);
                this.dispose();
            }
        } else {
            // Login failed
            JOptionPane.showMessageDialog(this, "Invalid username/email or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String getUserRole(int userId) {
        try (Connection conn = DbConnection.getConnection()) {
            String sql = "SELECT role FROM users WHERE user_id = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, userId);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                return rs.getString("role");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    private User validateLogin(String usernameOrEmail, String password) {
        try (Connection conn = DbConnection.getConnection()) {
            // Update the SQL query to select the 'active' column
            String sql = "SELECT user_id, username, role, active FROM users WHERE (username = ? OR email = ?) AND password = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, usernameOrEmail);
            stmt.setString(2, usernameOrEmail);
            stmt.setString(3, password);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                // Retrieve the necessary data from the ResultSet object
                int userId = rs.getInt("user_id");
                String username = rs.getString("username");
                String role = rs.getString("role"); // Retrieve role from database
                int active = rs.getInt("active"); // Retrieve active status

                // Create a User object with the retrieved data
                User user = new User(userId, username, role, active); // Add active parameter
                return user;  // Return the User object if login is successful
            } else {
                return null; // Return null if login failed
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public class User {

        private int userId;
        private String username;
        private String role; // Role field
        private int active; // New field for active status

        // Updated constructor to include active parameter
        public User(int userId, String username, String role, int active) {
            this.userId = userId;
            this.username = username;
            this.role = role; // Initialize role
            this.active = active; // Initialize active status
        }

        public int getUserId() {
            return userId;
        }

        public String getUsername() {
            return username;
        }

        public String getRole() { // Getter for role
            return role;
        }

        public int getActive() { // Getter for active status
            return active;
        }

    }//GEN-LAST:event_jLogButtonActionPerformed

    private void JRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRegButtonActionPerformed
        // TODO add your handling code here:
         new LibRegister().setVisible(true);
        this.dispose(); // Optionally close the login form
    }//GEN-LAST:event_JRegButtonActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LibLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JRegButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jLogButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
