/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mylibrary;
import javax.swing.JOptionPane; 
import java.sql.Connection;
import java.sql.DriverManager; 
import java.sql.PreparedStatement;
import java.sql.SQLException; 
/**
 *
 * @author ADMIN
 */
public class LibRegister extends javax.swing.JFrame {

    /**
     * Creates new form LibRegister
     */
    public LibRegister() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JNamefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JUsernameFld = new javax.swing.JTextField();
        JEmailFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPassField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        JRePassFld = new javax.swing.JPasswordField();
        SignUp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Jloginproceed = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setPreferredSize(new java.awt.Dimension(800, 540));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 135, 135));
        jPanel1.setPreferredSize(new java.awt.Dimension(319, 520));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\MyLibraryy\\src\\bgg (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(445, 0, 340, 520);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(146, 6, 186, 45);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 61, 83, 19);

        JNamefield.setBackground(new java.awt.Color(238, 248, 251));
        JNamefield.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JNamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(JNamefield);
        JNamefield.setBounds(43, 86, 375, 31);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 129, 83, 19);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 197, 83, 19);

        JUsernameFld.setBackground(new java.awt.Color(238, 248, 251));
        JUsernameFld.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JUsernameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUsernameFldActionPerformed(evt);
            }
        });
        getContentPane().add(JUsernameFld);
        JUsernameFld.setBounds(43, 154, 375, 31);

        JEmailFld.setBackground(new java.awt.Color(238, 248, 251));
        JEmailFld.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JEmailFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmailFldActionPerformed(evt);
            }
        });
        getContentPane().add(JEmailFld);
        JEmailFld.setBounds(43, 222, 375, 31);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(43, 259, 83, 19);

        jPassField.setBackground(new java.awt.Color(238, 248, 251));
        jPassField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPassField);
        jPassField.setBounds(43, 284, 375, 31);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Re-type Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(43, 327, 138, 19);

        JRePassFld.setBackground(new java.awt.Color(238, 248, 251));
        JRePassFld.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JRePassFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRePassFldActionPerformed(evt);
            }
        });
        getContentPane().add(JRePassFld);
        JRePassFld.setBounds(43, 352, 375, 31);

        SignUp.setBackground(new java.awt.Color(202, 218, 220));
        SignUp.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SignUp.setText("Sign up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp);
        SignUp.setBounds(190, 390, 100, 26);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Already have an account?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(69, 442, 186, 19);

        Jloginproceed.setBackground(new java.awt.Color(195, 202, 203));
        Jloginproceed.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Jloginproceed.setText("Login");
        Jloginproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JloginproceedActionPerformed(evt);
            }
        });
        getContentPane().add(Jloginproceed);
        Jloginproceed.setBounds(261, 439, 72, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\MyLibrary\\src\\1.png")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 450, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JNamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNamefieldActionPerformed
        // TODO add your handling code here:
        JUsernameFld.requestFocus();
    }//GEN-LAST:event_JNamefieldActionPerformed

    private void JUsernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUsernameFldActionPerformed
        // TODO add your handling code here:
         JEmailFld.requestFocus();
    }//GEN-LAST:event_JUsernameFldActionPerformed

    private void JEmailFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmailFldActionPerformed
        // TODO add your handling code here:
        jPassField.requestFocus();
        
    }//GEN-LAST:event_JEmailFldActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        String name = JNamefield.getText();
        String username = JUsernameFld.getText();
        String email = JEmailFld.getText();
        String password = new String(jPassField.getPassword()); // Original password
        String retypePassword = new String(JRePassFld.getPassword()); // Retyped password

        // 2. Validate the inputs (basic validation, you can enhance it)
        if (name.isEmpty() || username.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Check if passwords match
        if (!password.equals(retypePassword)) {
            // Show error message that passwords do not match
            JOptionPane.showMessageDialog(this, "Passwords do not match. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Save the user data to the database (assuming the DB connection is set up)
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_db", "root", "");
            String query = "INSERT INTO users (full_name, username, email, password) VALUES (?, ?, ?, ?)";

            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, name);
            ps.setString(2, username);
            ps.setString(3, email);
            ps.setString(4, password);

            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Optionally, redirect to login screen
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            ps.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        LibLogin loginWindow = new LibLogin();
        loginWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUpActionPerformed

    private void JloginproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JloginproceedActionPerformed
        // TODO add your handling code here:
        LibLogin login = new LibLogin();
        login.setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_JloginproceedActionPerformed

    private void jPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassFieldActionPerformed
        // TODO add your handling code here:
        JRePassFld.requestFocus();
    }//GEN-LAST:event_jPassFieldActionPerformed

    private void JRePassFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRePassFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRePassFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LibRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JEmailFld;
    private javax.swing.JTextField JNamefield;
    private javax.swing.JPasswordField JRePassFld;
    private javax.swing.JTextField JUsernameFld;
    private javax.swing.JButton Jloginproceed;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassField;
    // End of variables declaration//GEN-END:variables
}
